# Generated by Django 5.2.8 on 2026-01-18 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0030_adjudicator_registration_status_and_more'),
        ('registration', '0002_invitation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('bc', 'checkbox'), ('bs', 'yes/no (dropdown)'), ('i', 'integer (textbox)'), ('is', 'integer scale'), ('f', 'float'), ('t', 'text'), ('tl', 'long text'), ('ss', 'select one'), ('ms', 'select multiple'), ('dt', 'date + time')], max_length=2, verbose_name='answer type'),
        ),
        migrations.CreateModel(
            name='IndependentAdjudicatorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjudicator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='participants.adjudicator', verbose_name='adjudicator')),
            ],
            options={
                'verbose_name': 'independent adjudicator application',
                'verbose_name_plural': 'independent adjudicator applications',
            },
        ),
    ]
